2019-03-18 23:50:21 [scrapy.core.engine] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/home/zhangyanqing/anaconda3/envs/spider/lib/python3.6/site-packages/scrapy/core/engine.py", line 127, in _next_request
    request = next(slot.start_requests)
  File "/home/zhangyanqing/anaconda3/envs/spider/lib/python3.6/site-packages/scrapy/spiders/__init__.py", line 85, in start_requests
    yield Request(url, dont_filter=True)
  File "/home/zhangyanqing/anaconda3/envs/spider/lib/python3.6/site-packages/scrapy/http/request/__init__.py", line 25, in __init__
    self._set_url(url)
  File "/home/zhangyanqing/anaconda3/envs/spider/lib/python3.6/site-packages/scrapy/http/request/__init__.py", line 62, in _set_url
    raise ValueError('Missing scheme in request url: %s' % self._url)
ValueError: Missing scheme in request url: 
